import type { ActivityEntityType } from "@/lib/activity/log";

const ENTITY_LABELS: Record<ActivityEntityType, string> = {
  client: "Client",
  quotation: "Quotation",
  project: "Project",
  invoice: "Invoice",
  payment: "Payment",
  recurring_schedule: "Recurring schedule",
  work_item: "Work item",
};

const ACTION_VERBS: Record<string, string> = {
  created: "created",
  created_from_quotation: "created from a quotation",
  created_from_milestone: "created from a milestone",
  created_from_recurring_schedule: "generated by a recurring schedule",
  sent: "sent",
  cancelled: "cancelled",
  archived: "archived",
  reactivated: "reactivated",
  recorded: "recorded",
  active: "resumed",
  paused: "paused",
  ended: "ended",
  client_accepted: "accepted by the client",
  client_rejected: "declined by the client",
  client_changes_requested: "sent back for changes by the client",
  email_sent: "emailed to the client",
  email_skipped: "email not sent",
  email_failed: "email failed to send",
  status_changed: "status changed",
  completed: "completed",
  deleted: "deleted",
};

export function describeActivity(
  entityType: string,
  action: string,
  metadata?: Record<string, unknown> | null,
): string {
  const entityLabel = ENTITY_LABELS[entityType as ActivityEntityType] ?? entityType;
  const verb = ACTION_VERBS[action] ?? action.replace(/_/g, " ");

  if (entityType === "work_item" && action === "status_changed" && metadata?.from && metadata?.to) {
    const title = typeof metadata.title === "string" ? `"${metadata.title}"` : "Work item";
    return `${title} moved from ${STATUS_LABEL(metadata.from)} to ${STATUS_LABEL(metadata.to)}`;
  }

  const label =
    typeof metadata?.title === "string"
      ? metadata.title
      : typeof metadata?.name === "string"
        ? metadata.name
        : null;

  return label ? `${entityLabel} ${verb} — ${label}` : `${entityLabel} ${verb}`;
}

function STATUS_LABEL(value: unknown): string {
  const map: Record<string, string> = {
    todo: "To Do",
    in_progress: "In Progress",
    blocked: "Blocked",
    completed: "Completed",
  };
  return typeof value === "string" ? (map[value] ?? value) : String(value);
}
