import type { ActivityEntityType } from "@/lib/activity/log";

const ENTITY_LABELS: Record<ActivityEntityType, string> = {
  client: "Client",
  quotation: "Quotation",
  project: "Project",
  invoice: "Invoice",
  payment: "Payment",
  recurring_schedule: "Recurring schedule",
};

const ACTION_VERBS: Record<string, string> = {
  created: "created",
  created_from_quotation: "created from a quotation",
  created_from_milestone: "created from a milestone",
  created_from_recurring_schedule: "generated by a recurring schedule",
  sent: "sent",
  cancelled: "cancelled",
  archived: "archived",
  reactivated: "reactivated",
  recorded: "recorded",
  active: "resumed",
  paused: "paused",
  ended: "ended",
  client_accepted: "accepted by the client",
  client_rejected: "declined by the client",
  client_changes_requested: "sent back for changes by the client",
};

export function describeActivity(entityType: string, action: string): string {
  const entityLabel = ENTITY_LABELS[entityType as ActivityEntityType] ?? entityType;
  const verb = ACTION_VERBS[action] ?? action.replace(/_/g, " ");
  return `${entityLabel} ${verb}`;
}
